/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AuthModal: typeof import('./components/authentication/AuthModal.vue')['default']
    Chat: typeof import('./gameComponents/ChatPage.vue')['default']
    CreateLobbyDialog: typeof import('./components/lobbyComponents/CreateLobbyDialog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    JoinLobbyDialog: typeof import('./components/lobbyComponents/JoinLobbyDialog.vue')['default']
    Lobby: typeof import('./components/Lobby.vue')['default']
    Login: typeof import('./components/authentication/Login.vue')['default']
    NavBar: typeof import('./components/navbar/NavBar.vue')['default']
    PixiCanvas: typeof import('./components/canvas/PixiCanvas.vue')['default']
    Register: typeof import('./components/authentication/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WordChoice: typeof import('./components/canvas/WordChoice.vue')['default']
  }
}
